stuck at a univalue undefined ref problem
Running
```bash
./autogen.sh
./configure --enable-daemon --with-gui=qt5
--enable-debug
```
results to a situation where a bunch of undefined reference errors
are displayed before the compilation process exits.

```
/bin/bash ./libtool  --tag=CC   --mode=link gcc -std=gnu99 -I./incl
ude -g -O2 -W -std=gnu99 -pedantic -Wno-unused-function -Wno-long-l
ong -Wno-overlength-strings -g3 -O0 -DDEBUG   -o libbtc.la -rpath /
usr/local/lib src/libbtc_la-sha2.lo src/libbtc_la-utils.lo src/libb
tc_la-base58.lo src/libbtc_la-ripemd160.lo src/libbtc_la-bip32.lo s
rc/libbtc_la-ecc_libsecp256k1.lo src/libbtc_la-random.lo src/libbtc
_la-vector.lo src/libbtc_la-buffer.lo src/libbtc_la-cstr.lo src/lib
btc_la-serialize.lo src/libbtc_la-tx.lo src/libbtc_la-script.lo src
/libbtc_la-ecc_key.lo src/libbtc_la-aes.lo src/secp256k1/libsecp256
k1.la
libtool: link: rm -fr  .libs/libbtc.a .libs/libbtc.la .libs/libbtc.
lai .libs/libbtc.so .libs/libbtc.so.0 .libs/libbtc.so.0.0.0
libtool: link: gcc -shared  -fPIC -DPIC  src/.libs/libbtc_la-sha2.o
 src/.libs/libbtc_la-utils.o src/.libs/libbtc_la-base58.o src/.libs
/libbtc_la-ripemd160.o src/.libs/libbtc_la-bip32.o src/.libs/libbtc
_la-ecc_libsecp256k1.o src/.libs/libbtc_la-random.o src/.libs/libbt
c_la-vector.o src/.libs/libbtc_la-buffer.o src/.libs/libbtc_la-cstr
.o src/.libs/libbtc_la-serialize.o src/.libs/libbtc_la-tx.o src/.li
bs/libbtc_la-script.o src/.libs/libbtc_la-ecc_key.o src/.libs/libbt
c_la-aes.o   -Wl,-rpath -Wl,/src/src/libbtc/src/secp256k1/.libs src
/secp256k1/.libs/libsecp256k1.so  -O2 -O0   -Wl,-soname -Wl,libbtc.
so.0 -o .libs/libbtc.so.0.0.0
libtool: link: (cd ".libs" && rm -f "libbtc.so.0" && ln -s "libbtc.
so.0.0.0" "libbtc.so.0")
libtool: link: (cd ".libs" && rm -f "libbtc.so" && ln -s "libbtc.so
.0.0.0" "libbtc.so")
libtool: link: /usr/bin/ar cru .libs/libbtc.a  src/libbtc_la-sha2.o
 src/libbtc_la-utils.o src/libbtc_la-base58.o src/libbtc_la-ripemd1
60.o src/libbtc_la-bip32.o src/libbtc_la-ecc_libsecp256k1.o src/lib
btc_la-random.o src/libbtc_la-vector.o src/libbtc_la-buffer.o src/l
ibbtc_la-cstr.o src/libbtc_la-serialize.o src/libbtc_la-tx.o src/li
bbtc_la-script.o src/libbtc_la-ecc_key.o src/libbtc_la-aes.o
libtool: link: /usr/bin/ranlib .libs/libbtc.a
libtool: link: ( cd ".libs" && rm -f "libbtc.la" && ln -s "../libbt
c.la" "libbtc.la" )
make[3]: Leaving directory `/src/src/libbtc'
  AR       libdbb.a
  CXX      bitpaywalletclient/libbpwalletclient_a-bpwalletclient.o
  AR       libbpwalletclient.a
  CXX      dbb_cli-dbb_cli.o
  CXX      dbb_cli-dbb_util.o
  CXXLD    dbb-cli
dbb_cli-dbb_cli.o: In function `main':
/src/src/dbb_cli.cpp:432: undefined reference to `find_value(UniVal
ue const&, std::string const&)'
/src/src/dbb_cli.cpp:450: undefined reference to `UniValue::write(u
nsigned int, unsigned int) const'
libdbb.a(libdbb_a-dbb.o): In function `DBB::decryptAndDecodeCommand
(std::string const&, std::string const&, std::string&, bool)':
/src/src/libdbb/dbb.cpp:568: undefined reference to `find_value(Uni
Value const&, std::string const&)'
/src/src/libdbb/dbb.cpp:570: undefined reference to `find_value(Uni
Value const&, std::string const&)'
/src/src/libdbb/dbb.cpp:572: undefined reference to `UniValue::get_
str() const'
/src/src/libdbb/dbb.cpp:575: undefined reference to `find_value(Uni
Value const&, std::string const&)'
/src/src/libdbb/dbb.cpp:579: undefined reference to `UniValue::get_
str() const'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)
@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_replace(unsigned long, unsigned long, char const*, unsigned lo
ng)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `vtable for s
td::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::all
ocator<char> >@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>
, std::allocator<char> > const&)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_istringstream<char, std::char_traits<char>, std::allocator<
char> >::~basic_istringstream()@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `vtable for s
td::__cxx11::basic_istringstream<char, std::char_traits<char>, std:
:allocator<char> >@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::runtime
_error::runtime_error(char const*)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `vtable for s
td::__cxx11::basic_ostringstream<char, std::char_traits<char>, std:
:allocator<char> >@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::_M_mutate(unsigned long, unsigned long, char const*, unsigned lon
g)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::reserve(unsigned long)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `VTT for std:
:__cxx11::basic_istringstream<char, std::char_traits<char>, std::al
locator<char> >@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_stringbuf<char, std::char_traits<char>, std::allocator<char
> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_ostringstream<char, std::char_traits<char>, std::allocator<
char> >::~basic_ostringstream()@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `VTT for std:
:__cxx11::basic_ostringstream<char, std::char_traits<char>, std::al
locator<char> >@GLIBCXX_3.4.21'
univalue/.libs/libunivalue.so: undefined reference to `operator del
ete(void*, unsigned long)@CXXABI_1.3.9'
univalue/.libs/libunivalue.so: undefined reference to `std::__cxx11
::basic_string<char, std::char_traits<char>, std::allocator<char> >
::compare(char const*) const@GLIBCXX_3.4.21'
collect2: error: ld returned 1 exit status
make[2]: *** [dbb-cli] Error 1
make[2]: Leaving directory `/src/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/src/src'
```